version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:ap-northeast-1:947106514667:task-definition/cfn-todo-backend:26
        LoadBalancerInfo:
          ContainerName: 'cfn-task-definition'
          ContainerPort: 3000
